name: hyper_customer
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter

  dio: ^4.0.6
  shared_preferences: ^2.0.15
  connectivity_plus: ^2.3.5
  fluttertoast: ^8.0.9
  flutter_svg: ^1.1.1+1
  flutter_native_splash: ^2.2.4
  video_player: ^2.4.5
  chewie: ^1.3.4
  flutter_screenutil: ^5.5.3+2
  antdesign_icons: ^0.0.3
  pull_to_refresh: ^2.0.0
  percent_indicator: ^4.2.2
  qr_code_scanner: ^1.0.0
  currency_text_input_formatter: ^2.1.7
  webview_flutter: ^3.0.4
  jwt_decode: ^0.3.1
  lottie: ^1.3.0
  cached_network_image: ^3.2.1
  shimmer: ^2.0.0
  app_links: ^3.2.0
  intl: ^0.17.0
  url_launcher: ^6.1.5
  flutter_vibrate: ^1.3.0
  flutter_map: ^2.0.0
  flutter_map_location_marker: ^4.1.3
  geolocator: ^9.0.1
  tiengviet: ^0.5.0
  latlong2: ^0.8.1
  polyline_do: ^0.1.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#00CD7F"
  image: assets/img/ic_launcher_white.png
  # color: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/img/
    - assets/mp4/
    - assets/lottiefiles/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Thin.ttf
  #       - asset: assets/fonts/Roboto-Light.ttf
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Medium.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #       - asset: assets/fonts/Roboto-Black.ttf

  #       - asset: assets/fonts/Roboto-ThinItalic.ttf
  #         style: italic
  #       - asset: assets/fonts/Roboto-LightItalic.ttf
  #         style: italic
  #       - asset: assets/fonts/Roboto-Italic.ttf
  #         style: italic
  #       - asset: assets/fonts/Roboto-MediumItalic.ttf
  #         style: italic
  #       - asset: assets/fonts/Roboto-BoldItalic.ttf
  #         style: italic
  #       - asset: assets/fonts/Roboto-BlackItalic.ttf
  #         style: italic
